### PR TITLE
LANG-1682 Adding StringUtils.startsWithAnyIgnoreCase method

### PR DESCRIPTION
**Pull request by Enigo**
Adding `StringUtils.startsWithAnyIgnoreCase` to have more flexibility.
Based on the existing `startsWith` method

### CODE REVIEW

**Comment by LarsBodewig** [comment]
Concurrent open PR for LANG-1682: #852

**Comment by Enigo** [comment]
Hey @garydgregory 
any chance for this PR to be reviewed and merged?
thanks!

**Comment by garydgregory** [comment]
Needs further thought: I don't think it makes sense to overcrowd this class with more "ignore case" versions of methods and to also have "any" or "all" versions of methods. Instead, we should consider another design, maybe having a string util class with a subclass for case sensitive and another for cases insensitive matches, for example.

**Comment by Enigo** [comment]
I'm not sure if that would be user-friendly, as most users are used to one single class for all operations with strings, numbers, lists, sets etc.
That would be quite a drastic change
But I do agree that this class is quite crowded already

**Comment by garydgregory** [comment]
@Enigo @LarsBodewig 
Closing: Please try your use case with the Strings class in git master and snapshot builds.

**Pull request closed without merging**
