### PR TITLE
Add GenericArrayType support to TypeUtils.containsTypeVariables

### PR DESCRIPTION
**Pull request by dimitrovchi**
Currently, org.apache.commons.lang3.reflect.TypeUtils#containsTypeVariables doesn't contain a special case for GenericArrayType like E[], so if the passed argument is a GenericArrayType instance containing type variables, this method will return false.

### CODE REVIEW

**Comment by dimitrovchi** [comment]
Please look at the CI build. There was an error during artifact fetching:

`[ERROR] Failed to execute goal org.codehaus.mojo:clirr-maven-plugin:2.8:check (default-cli) on project commons-lang3: Execution default-cli of goal org.codehaus.mojo:clirr-maven-plugin:2.8:check failed: Plugin org.codehaus.mojo:clirr-maven-plugin:2.8 or one of its dependencies could not be resolved: Could not transfer artifact org.apache.bcel:bcel:jar:6.0 from/to google-maven-central (https://maven-central.storage-download.googleapis.com/repos/central/data/): GET request of: org/apache/bcel/bcel/6.0/bcel-6.0.jar from google-maven-central failed: 
`
resulting in overall build failure. Is there a possibility to rerun checks without committing anything else?

**Comment by kinow** [comment]
> resulting in overall build failure. Is there a possibility to rerun checks without committing anything else?

Restarted in Travis interface the job that failed (JDK: openjdk11 Java).

**Comment by dimitrovchi** [comment]
I've added the test: https://github.com/apache/commons-lang/pull/437/files
Please look at CI logs again: the logs show checkstyle rules violations in `Functions.java` but I didn't change that file:
```
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[148] (javadoc) JavadocMethod: Expected @return tag.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[148,59] (javadoc) JavadocMethod: Expected @param tag for 'pRunnable'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[149,5] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[161] (javadoc) JavadocMethod: Expected @return tag.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[161,20] (javadoc) JavadocMethod: Expected @param tag for '<I>'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[161,64] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[161,68] (javadoc) JavadocMethod: Expected @param tag for 'pConsumer'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[174] (javadoc) JavadocMethod: Expected @return tag.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[174,20] (javadoc) JavadocMethod: Expected @param tag for '<O>'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[174,64] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[174,68] (javadoc) JavadocMethod: Expected @param tag for 'pCallable'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[187] (javadoc) JavadocMethod: Expected @return tag.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[187,20] (javadoc) JavadocMethod: Expected @param tag for '<I1>'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[187,22] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[187,23] (javadoc) JavadocMethod: Expected @param tag for '<I2>'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[187,40] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[187,79] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[187,82] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[187,86] (javadoc) JavadocMethod: Expected @param tag for 'pConsumer'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[200] (javadoc) JavadocMethod: Expected @return tag.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[200,20] (javadoc) JavadocMethod: Expected @param tag for '<I>'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[200,21] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[200,22] (javadoc) JavadocMethod: Expected @param tag for '<O>'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[200,35] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[200,68] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[200,70] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[200,74] (javadoc) JavadocMethod: Expected @param tag for 'pFunction'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[213] (javadoc) JavadocMethod: Expected @return tag.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[213,20] (javadoc) JavadocMethod: Expected @param tag for '<I1>'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[213,22] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[213,23] (javadoc) JavadocMethod: Expected @param tag for '<I2>'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[213,25] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[213,26] (javadoc) JavadocMethod: Expected @param tag for '<O>'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[213,42] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[213,45] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[213,83] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[213,86] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[213,88] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[213,92] (javadoc) JavadocMethod: Expected @param tag for 'pFunction'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[226] (javadoc) JavadocMethod: Expected @return tag.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[226,20] (javadoc) JavadocMethod: Expected @param tag for '<I>'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[226,67] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[226,71] (javadoc) JavadocMethod: Expected @param tag for 'pPredicate'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[239] (javadoc) JavadocMethod: Expected @return tag.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[239,20] (javadoc) JavadocMethod: Expected @param tag for '<I1>'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[239,22] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[239,23] (javadoc) JavadocMethod: Expected @param tag for '<I2>'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[239,41] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[239,82] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[239,85] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[239,89] (javadoc) JavadocMethod: Expected @param tag for 'pPredicate'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[252] (javadoc) JavadocMethod: Expected @return tag.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[252,20] (javadoc) JavadocMethod: Expected @param tag for '<O>'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[252,64] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[252,68] (javadoc) JavadocMethod: Expected @param tag for 'pSupplier'.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[399,21] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/main/java/org/apache/commons/lang3/Functions.java:[399,67] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/test/java/org/apache/commons/lang3/FunctionsTest.java:[42,15] (imports) UnusedImports: Unused import - org.junit.jupiter.api.Assertions.assertFalse.
[ERROR] src/test/java/org/apache/commons/lang3/FunctionsTest.java:[171,55] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/test/java/org/apache/commons/lang3/FunctionsTest.java:[171,96] (blocks) LeftCurly: '{' at column 96 should have line break after.
[ERROR] src/test/java/org/apache/commons/lang3/FunctionsTest.java:[180,9] (whitespace) FileTabCharacter: File contains tab characters (this is the first instance).
[ERROR] src/test/java/org/apache/commons/lang3/FunctionsTest.java:[214] (regexp) RegexpSingleline: Line has trailing spaces.
[ERROR] src/test/java/org/apache/commons/lang3/FunctionsTest.java:[260] (regexp) RegexpSingleline: Line has trailing spaces.
[ERROR] src/test/java/org/apache/commons/lang3/FunctionsTest.java:[260,98] (blocks) LeftCurly: '{' at column 98 should have line break after.
[ERROR] src/test/java/org/apache/commons/lang3/FunctionsTest.java:[308,41] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/test/java/org/apache/commons/lang3/FunctionsTest.java:[308,49] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/test/java/org/apache/commons/lang3/FunctionsTest.java:[312,33] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/test/java/org/apache/commons/lang3/FunctionsTest.java:[357,42] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/test/java/org/apache/commons/lang3/FunctionsTest.java:[357,52] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/test/java/org/apache/commons/lang3/FunctionsTest.java:[357,60] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/test/java/org/apache/commons/lang3/FunctionsTest.java:[361,34] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/test/java/org/apache/commons/lang3/FunctionsTest.java:[361,44] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/test/java/org/apache/commons/lang3/FunctionsTest.java:[395,55] (whitespace) WhitespaceAfter: ',' is not followed by whitespace.
[ERROR] src/test/java/org/apache/commons/lang3/FunctionsTest.java:[395,92] (blocks) LeftCurly: '{' at column 92 should have line break after.
```

**Comment by dimitrovchi** [comment]
The same **false-positive** build failure happened to https://travis-ci.org/apache/commons-lang/jobs/575873214

**Comment by garydgregory** [comment]
Closing: This already works in git master. I added the test only to git master. TY.

**Pull request closed without merging**
