### PR TITLE
Removed use of restricted identifier

### PR DESCRIPTION
**Pull request by fykidwai**
Modified variable name from 'var' to 'key' to avoid confusion in future with java 11+ versions

### CODE REVIEW

**Review by XenoAmess — APPROVED** [review]

**Comment by garydgregory** [comment]
FYI, var is a Java 10 feature.

**Comment by fykidwai** [comment]
@XenoAmess: I don't have write access to merge the PR..!!

**Comment by garydgregory** [comment]
Is this an issue that really need solving?

**Comment by garydgregory** [comment]
@fykidwai May you please rebase on git master so we can see if we get green builds?

**Comment by garydgregory** [comment]
Closing: No action/feedback from OP since the last query. The build is green on GitHub for Java 17 anyway.

**Pull request closed without merging**
