### PR TITLE
MINOR: Changed to simpler + concat as it's more readable and StringBuilder d…

### PR DESCRIPTION
**Pull request by Serwios**
…oesn't make a lot of sense here

Here StringBuilder doesn't giving significant benefit. The generated bytecode typically uses a StringBuilder for such concatenations automatically so for better readability I changed for simple + concat.

Thanks for your contribution to [Apache Commons](https://commons.apache.org/)! Your help is appreciated!

Didn't add tests cause not needed

Before you push a pull request, review this list:

- [X] Read the [contribution guidelines](CONTRIBUTING.md) for this project.
- [X] Run a successful build using the default [Maven](https://maven.apache.org/) goal with `mvn`; that's `mvn` on the command line by itself.
- [X] Write unit tests that match behavioral changes, where the tests fail if the changes to the runtime are not applied. This may not always be possible but is a best-practice.
- [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [X] Each commit in the pull request should have a meaningful subject line and body. Note that commits might be squashed by a maintainer on merge.

### CODE REVIEW

**Comment by garydgregory** [comment]
-1 @Serwios 

This is not a good idea. You've removed the guarantee `StringBuilder` provides of not using synchronized code, which is unnecessary here.

**Comment by Serwios** [comment]
Hi, in JDK 8 and earlier, + compiles to StringBuilder. From JDK 9 onward, it uses StringConcatFactory, which optimizes simple cases like this to behave similarly to StringBuilder.

This guarantee should be present as return type.getLabel() + ' ' + arch.getLabel(); is compiled to return new StringBuilder().append(type.getLabel()).append(' ').append(arch.getLabel()).toString();

https://stackoverflow.com/questions/11942368/why-use-stringbuilder-explicitly-if-the-compiler-converts-string-concatenation-t

**Comment by ppkarwasz** [comment]
@Serwios,

String concatenation is IMHO more readable than the equivalent `StringBuilder` construction, but changing this in a single method that is probably not used and certainly not tested, doesn't make sense to me.

Could you go the extra mile of:

- proposing on the `dev@commons.apache.org` mailing list to replace simple `StringBuilder` constructs with string concatenation. Whether to use `StringBuilder`, string concatenation or `String.format()` is mostly a matter of taste and IDEs can refactor each one of these formats into another.
- if the community accepts the change, apply it **everywhere**?

**Comment by Serwios** [comment]
> @Serwios,
> 
> String concatenation is IMHO more readable than the equivalent `StringBuilder` construction, but changing this in a single method that is probably not used and certainly not tested, doesn't make sense to me.
> 
> Could you go the extra mile of:
> 
> * proposing on the `dev@commons.apache.org` mailing list to replace simple `StringBuilder` constructs with string concatenation. Whether to use `StringBuilder`, string concatenation or `String.format()` is mostly a matter of taste and IDEs can refactor each one of these formats into another.
> * if the community accepts the change, apply it **everywhere**?

I’ll propose this discussion on the dev@commons.apache.org mailing list to determine if there’s a preference within the team for standardizing string concatenation over StringBuilder or other alternatives like String.format(). If the community supports this, I’m happy to take the lead on refactoring similar cases project-wide to ensure consistency.

IMHO: Regarding standardization, I believe it’s about establishing a common pattern that promotes code readability and maintainability. Having a generally accepted approach ensures that contributors don’t waste time debating minor stylistic differences and instead focus on improving functionality. It also makes the codebase easier to review, debug, and extend, especially for new contributors.

**Comment by garydgregory** [comment]
I like @ppkarwasz 's idea. I don't want to review one-offs.

**Pull request closed without merging**
