### PR TITLE
Convert tests for Validate.isTrue overloads to @Nested test

### PR DESCRIPTION
**Pull request by britter**
Proposal for a better structure of tests using `@Nested`. Each method should have it's own `@Nested` container which is called like the method. Inside that container each overload has it's own `@Nested` container. I did this for `Validate.isTrue` to show the approach.

### CODE REVIEW

**Comment by britter** [comment]
@kinow @PascalSchumacher @chtompki WDYT?

**Comment by PascalSchumacher** [comment]
+1

**Comment by britter** [comment]
Okay, as there is positive feedback for this change, I'm going to migrate the whole `ValidateTest` to this style and then merge it 👍

**Comment by britter** [comment]
Build failure seems to be unrelated.

**Pull request merged**
