### PR TITLE
Rename method and fix typo.

### PR DESCRIPTION
**Pull request by arturobernalg**
**NOTE**: Broke binary.

### CODE REVIEW

**Comment by garydgregory** [comment]
Is this a duplicate PR?

**Comment by garydgregory** [comment]
Is this PR a duplicate?

**Comment by arturobernalg** [comment]
> Is this PR a duplicate?

Yes. Similar to https://github.com/apache/commons-lang/pull/940 but without binary compatibility.

**Comment by arturobernalg** [comment]
close in favor of  `[940](https://github.com/apache/commons-lang/pull/940)`

**Pull request closed without merging**
