### PR TITLE
Make diff result extends pair

### PR DESCRIPTION
**Pull request by XenoAmess**
for compatibility to Diff who extends Pair as well.

### CODE REVIEW

**Comment by garydgregory** [comment]
My only concern here is what JApiCmp reports:
```
mvn install -P japicmp japicmp:cmp
```
Yields:
```
MODIFIED (Serializable incompatible(!): superclass modified) public class org.apache.commons.lang3.builder.DiffResult
```
Which I think means it breaks binary compatibility. Can someone confirm either way?

**Comment by Stzx** [comment]
@garydgregory 

+1

`DiffResult` extend `Pair` and does break the serialization function of `Pair`.

**Comment by XenoAmess** [comment]
> @garydgregory
> 
> +1
> 
> `DiffResult` extend `Pair` and does break the serialization function of `Pair`.

My bad. I forgot to add serialVersionUID for it.

**Comment by garydgregory** [comment]
I created https://issues.apache.org/jira/browse/LANG-1503 to bring in the changes to the three Pair classes. Note that there are only new factory methods. The additional constructors are not needed. I think it is also better design to have the conversion work done in factory methods and the results funneled to the constructors.

The DiffResult change of superclass is not brought in as it would break binary compatibility.
You can check this by running:
```
mvn clean package site -V -P jacoco -P japicmp
```
and checking the generated report in the site at `target\site\index.html` where you will see:
```
MODIFIED (Serializable incompatible(!): superclass modified) public class org.apache.commons.lang3.builder.DiffResult
```

**Comment by XenoAmess** [comment]
close as https://github.com/scope-demo/commons-lang/commit/aa3d92498e223ea051f3965d80b9428b4f5d9e98

**Pull request closed without merging**
