### PR TITLE
Fix typo on appendIfMissing javadoc

### PR DESCRIPTION
**Pull request by ptemplier**

### CODE REVIEW

**Comment by garydgregory** [comment]
Thank you for the PR. In Git master now.

**Comment by ptemplier** [comment]
:+1:

**Comment by garydgregory** [comment]
Looks like this has been fixed. This issue can be closed.

**Comment by kinow** [comment]
Placeholder ticket created https://issues.apache.org/jira/browse/LANG-1221

**Comment by kinow** [comment]
Adding an entry in changes.xml for that with dev= ggregory, with a message containing the closes #129 in order to close this pull request in GitHub and also keep track of the change.

**Pull request closed without merging**
