### PR TITLE
LANG-1290: Increase test coverage of org.apache.commons.lang3.ArrayUtils class

### PR DESCRIPTION
**Pull request by Abrasha**
- fix an issue with not getting Annotation in AnnotaionUtilsTest
- add tests to cover ArrayUtils

Increased coverage to ~98% lines of code and 100% methods.

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Thanks for the pull request! 👍 

>fix an issue with not getting Annotation in AnnotaionUtilsTest

Not sure what you fixed there. What is the reason of this change? Thanks!

**Comment by Abrasha** [comment]
@PascalSchumacher, no problem!

```
@Test
public void testAnnotationsOfDifferingTypes() {
    assertFalse(AnnotationUtils.equals(field1.getAnnotation(TestAnnotation.class), field4.getAnnotation(NestAnnotation.class)));
    assertFalse(AnnotationUtils.equals(field4.getAnnotation(NestAnnotation.class), field1.getAnnotation(TestAnnotation.class)));
}
```

This test is successful, but checks a different behaviour than expected.

`field4.getAnnotation(NestAnnotation.class)` is expected to return an annotation of type `NestAnnotation`, but actually it returns `null` because the Retention of annotation is set to default.

As a result, test did not cover quite important case.

**Comment by PascalSchumacher** [comment]
Great find! 👍 Thanks for the detailed explanation. :)
 
As this change is unrelated to improving the test coverage of ArrayUtils, it would be nice if you could move it to a separate commit.

**Comment by Abrasha** [comment]
@PascalSchumacher, thanks for note. I will separate it.

**Comment by PascalSchumacher** [comment]
Thanks! 👍

**Comment by Abrasha** [comment]
@PascalSchumacher sorry, just for ensure, have changed been merged? 
Status is: _Closed with unmerged commits_. It is a way of using patches, yes?

Thanks.

**Comment by PascalSchumacher** [comment]
Yes, the changes have been merged: 51b2cab

I think the commit is marked as unmerged, because I changed the commit message. But you are still listed as the author, so I guess everything is ok?

**Comment by PascalSchumacher** [comment]
It's the same for the other commit, see:

https://github.com/apache/commons-lang/commits/master

**Comment by Abrasha** [comment]
@PascalSchumacher, thanks, of course everything is ok.
I just wanted to understand the workflow.
(I am quiet new to Open Source)

**Comment by PascalSchumacher** [comment]
No problem. :)

When I started contributing to Open Source and using git and github I also had a lot of questions.

**Pull request closed without merging**
