### PR TITLE
LANG-781 Added methods to ObjectUtils class to check for null element…

### PR DESCRIPTION
**Pull request by vanta**
I've created this pull request to refresh the issue LANG-781 as I faced a lack of methods to check nulls in array.

### CODE REVIEW

**Comment by vanta** [comment]
Any update on this?

**Comment by garydgregory** [comment]
Yes:
- Thank you for the patch.
- The Javadoc has some bogus text, like starting with "<p></p>". You do not need that.
- Do not use a for-each loop to traverse an array. This creates an iterator when none is needed. Use a normal for loop, which will not create the extra Iterator to GC. This matters when a libraries is used on the critical path and/or environments trying to do low/no GC.

**Comment by PascalSchumacher** [comment]
@vanta It would be nice if you could update the pull request according to garys comments.

Thanks!

**Comment by vanta** [comment]
@garydgregory How bout `firstNonNull` method that exists since 2009 and uses for-each loop to iterate over array?

**Comment by garydgregory** [comment]
There is a discussion going on right now on the dev mailing list about for-each vs. for. Let's see how that plays out. See https://commons.apache.org/mail-lists.html

**Comment by PascalSchumacher** [comment]
Thanks! :+1: 

For each loop won the discussion, so I merged only the first commit.

@vanta Sorry for telling you to refactor to use a for loop.

**Comment by vanta** [comment]
@PascalSchumacher Nothing to sorry for :)

**Pull request closed without merging**
