### PR TITLE
Added new examples for rightPad method

### PR DESCRIPTION
**Pull request by esivakumar18**
Added new examples for `rightPad` method.

### CODE REVIEW

**Comment by garydgregory** [comment]
This does not help, it just makes things bigger without helping users IMO. The additional tests don't even increase code coverage, so there is really little value in even the new assertions IMO.

**Comment by esivakumar18** [comment]
> This does not help, it just makes things bigger without helping users IMO. The additional tests don't even increase code coverage, so there is really little value in even the new assertions IMO.

Hi @garydgregory  thank you for the comment. I have added this example to clear some confusion i.e., if we try to do padding on space, it will yield the same result without any padding. Kindly review again.

**Comment by esivakumar18** [comment]
@kinow could you please review this ?

**Comment by ecki** [comment]
I am also not sure if we need the samples, but i could see some use in explaining that blank is not special, in that case (“    “,3) (similar to („abc“,2) but with blanks is missing.

the sample and tests differ, i would use ,3 in both.

**Pull request closed without merging**
