### PR TITLE
[LANG-1426] Corrected usage examples in Javadocs

### PR DESCRIPTION
**Pull request by mikkomaunu**
Fixed documentation. No tests added because existings unit tests seam to cover these code examples reasonably well.

### CODE REVIEW

**Comment by garydgregory** [comment]
Why not also properly document legal inputs with `@throws`?

**Comment by mikkomaunu** [comment]
> 
> 
> Why not also properly document legal inputs with `@throws`?

Makes perfectly sense. Which approach is preferred:

One throws per Exception type:

`@throws IllegalArgumentException If {@code offset} or {@code maxWidth} is less than {@code 0} `

or:

```
@throws IllegalArgumentException If {@code offset} is less than {@code 0} 
@throws IllegalArgumentException If {@code maxWidth} is less than {@code 0}
```

**Comment by mikkomaunu** [comment]
Related theme, should one also fix tests that assert exceptions? Currently message does not describe too well why test failed, instead it often simply repeats Exception message. Also that does not alway match.

For example. Following assertion uses "maxWith cannot be negative" as message. That does not describe why test failed. Also, because first argument is validated first, actual message in exception is "offset cannot be negative" 
```

assertThrows(
                IllegalArgumentException.class,
                () -> StringUtils.truncate(null, Integer.MIN_VALUE, Integer.MIN_VALUE),
                "maxWith cannot be negative");
```

I see two approaches to fix this:
1) improve message (less code, changing order of parameter validation does not affect tests):
```
        assertThrows(
                IllegalArgumentException.class,
                () -> StringUtils.truncate(null, Integer.MIN_VALUE, Integer.MIN_VALUE),
                "Expected IllegalArgumentException when both offset and and maxWidth are negative");
```

2) improve message and assert also Exception message (significantly more code, does not play well when code does have bunch of unrelated assertions in one test method):

```
        final IllegalArgumentException exceptionWhenOffsetAndMaxWidthAreNegative = assertThrows(
                IllegalArgumentException.class,
                () -> StringUtils.truncate(null, Integer.MIN_VALUE, Integer.MIN_VALUE),
                "Expected IllegalArgumentException when both offset and and maxWidth are negative");
        assertEquals("offset cannot be negative", exceptionWhenOffsetAndMaxWidthAreNegative.getMessage(), "Wrong Exception message");
```

When exception is thrown because maxWidth is negative, then there is misspelling: "maxWith cannot be negative";

**Comment by garydgregory** [comment]
WRT `@throws`: One.

**Comment by garydgregory** [comment]
I we should do what makes the code easier to understand from the perspective of maintenance: If a new person looks at the test, what is best for them to understand what is being tested. What would make it easier to add another test. And so on.

**Comment by kinow** [comment]
I think @mikkomaunu has updated the PR with your suggestions @garydgregory . Should be good to be reviewed now :tada:

**Comment by garydgregory** [comment]
https://issues.apache.org/jira/browse/LANG-1426

**Pull request merged**
