### PR TITLE
Lang 740 - Memoizer implementation

### PR DESCRIPTION
**Pull request by jamessawle**
Enclosed is an implementation of the Memoizer class, along with some unit tests through the main flow of the code.

### CODE REVIEW

**Comment by britter** [comment]
Hello @jamessawle,

very nice, I'll try to have a look this weekend. Don't worry about coveralls. Looks like it is configured to strict. I'll look into that.

Benedikt

**Comment by jamessawle** [comment]
I can improve coverage of my class by two lines by throwing different types of exception (Runtime and Error); however, not sure how to fix the final two lines in the class that are unchecked.

With regards to the rest of the changes; I am unsure how what I did affected 40 other classes! That being said, I like the failure based on coverage; but maybe 0.1% would be a better ratio with the size of our code base.

**Comment by britter** [comment]
@jamessawle I've already brought this up on the ML. The coveralls failure is no blocker for me for integration. I think we will configure converalls with thresholds like max 3% drop and min 90% overall coverage.

br,
Benedikt

**Comment by britter** [comment]
@jamessawle Commons Lang has been migrated from svn to git. Because of this the main branch has been renamed to 'master'. Can you please rebase your work against the master branch? Thank you!

**Comment by jamessawle** [comment]
Closing to create a new pull request against the new branch.

**Pull request closed without merging**
