### PR TITLE
Adding junits for StandardToStringStyle

### PR DESCRIPTION
**Pull request by RahulNagekar**

### CODE REVIEW

**Comment by RahulNagekar** [comment]
This is my entry level checkin just to understand flow here, will get into more contribution once this is merged/accepted.

**Comment by RahulNagekar** [comment]
@garydgregory Any references on how can I ask for a review or get into contribution.

I am new to open source so.

**Comment by PascalSchumacher** [comment]
Thank for the contribution.

Could you please squash to the commits? Then I will merge the pull request.

**Comment by RahulNagekar** [comment]
> Thank for the contribution.
> 
> Could you please squash to the commits? Then I will merge the pull request.

Done :-)

**Comment by PascalSchumacher** [comment]
Thanks!

**Pull request closed without merging**
