### PR TITLE
Add ArrayUtils.isSameLength() to compare more array types

### PR DESCRIPTION
**Pull request by XenoAmess**
now it shall be able to compare different kinds of arrays.

### CODE REVIEW

**Comment by garydgregory** [comment]
Please resolve conflicts and add tests for the new code.

**Comment by XenoAmess** [comment]
@garydgregory  resolving conflicts and adding tests done.

**Comment by XenoAmess** [comment]
@garydgregory , anything we can do to get this moving?

**Comment by garydgregory** [comment]
-1 This is more simply implemented with what is in git master now. I did add the new tests though :-)

**Comment by XenoAmess** [comment]
> -1 This is more simply implemented with what is in git master now. I did add the new tests though :-)

@garydgregory Thanks.

**Pull request closed without merging**
