### PR TITLE
Adding junits for JsonToStringStyle

### PR DESCRIPTION
**Pull request by RahulNagekar**

### CODE REVIEW

**Comment by RahulNagekar** [comment]
This is ready for merge , could we please have this handled.

**Comment by kinow** [comment]
This project is maintained by volunteers @RahulNagekar. Please be patient as maintainers can be busy or under pressure with other issues, work, life, etc.

**Comment by chtompki** [comment]
I'm fairly indifferent about how the strings are declared as they are tests. The concatenation is a tad odd to me because it seems to be unnecessary. That said, I'm all for more tests. I say we pull this in and clean it up in `master` because having more tests is always a good thing.

**Comment by chtompki** [comment]
I'll try to get to this today.

**Comment by RahulNagekar** [comment]
Will post 1 more commit improving this. I am all agree with all comnents , its best to follow best practices.

**Comment by MarkDacek** [comment]
@chtompki This seems reasonable and passes both verify and checkstyle. Worth pulling in?

**Pull request merged**
