### PR TITLE
LANG-1146 Add helper method to SystemUtils.java for zOS identification

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
@britter Could you review? Thanks

**Comment by britter** [comment]
Hello @gliptak,

sorry for the delay. There are a lot of pending PRs but I don't have time for OSS at the moment :-( I'll have a look as soon as I have more time again.

Benedikt

**Comment by gliptak** [comment]
@garydgregory The one reference i'm seeing is at

http://public.dhe.ibm.com/common/ssi/ecm/zs/en/zsl03071usen/ZSL03071USEN.PDF

The system property os.arch for IBM SDK for z/OS, version 1.4.2 (31-bit)
versions and earlier had a value of 390. From Java 5.0 onwards, the value of
os.arch is s390.

I'm not sure of the "z/os" reference as described at:

http://www.java2s.com/Tutorial/Java/0120__Development/ConditionthatteststheOStype.htm

**Comment by gliptak** [comment]
Benedikt, would this be still of interest? Thanks

**Comment by garydgregory** [comment]
Can we come up a check that works on all version of z/OS?

**Comment by gliptak** [comment]
I do not have access to Java running on various mainframes. If somebody is able to list out the combinations, I'm open to code it.

**Comment by garydgregory** [comment]
Here are some sys props from one of our z/OS systems:

Start system properties (71):
  awt.toolkit = sun.awt.X11.XToolkit
  com.ibm.cpu.endian = big
  com.ibm.jcl.checkClassPath =
  com.ibm.oti.configuration = scar
  com.ibm.oti.jcl.build = 20150630_255633
  com.ibm.oti.shared.enabled = false
  com.ibm.oti.vm.bootstrap.library.path = /rsusr/java/IBM/J8.0_64/lib/s390x/compressedrefs:/rsusr/java/IBM/J8.0_64/lib/s390x
  com.ibm.oti.vm.library.version = 28
  com.ibm.packed.version = 2
  com.ibm.system.agent.path = /rsusr/java/IBM/J8.0_64/lib/s390x
  com.ibm.util.extralibs.properties =
  com.ibm.vm.bitmode = 64
  com.ibm.zero.version = 2
  file.encoding = IBM-1047
  file.encoding.pkg = sun.io
  file.separator = /
  ibm.signalhandling.rs = false
  ibm.signalhandling.sigchain = false
  ibm.signalhandling.sigint = true
  ibm.system.encoding = IBM-1047
  java.awt.fonts =
  java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
  java.awt.printerjob = sun.print.PSPrinterJob
  java.class.path = ***
  java.class.version = 52.0
  java.compiler = j9jit28
  java.endorsed.dirs = /rsusr/java/IBM/J8.0_64/lib/endorsed
  java.ext.dirs = /rsusr/java/IBM/J8.0_64/lib/ext
  java.fullversion = JRE 1.8.0 IBM J9 2.8 z/OS s390x-64 Compressed References 20150630_255633 (JIT enabled, AOT enabled)
J9VM - R28_jvm.28_20150630_1742_B255633
JIT  - tr.r14.java_20150625_95081.01
GC   - R28_jvm.28_20150630_1742_B255633_CMPRSS
J9CL - 20150630_255633
  java.home = /rsusr/java/IBM/J8.0_64
  java.io.tmpdir = /tmp
  java.library.path = ***
  java.runtime.name = Java(TM) SE Runtime Environment
  java.runtime.version = pmz6480sr1fp10-20150716_01 (SR1 FP10)
  java.specification.name = Java Platform API Specification
  java.specification.vendor = Oracle Corporation
  java.specification.version = 1.8
  java.util.prefs.PreferencesFactory = java.util.prefs.FileSystemPreferencesFactory
  java.vendor = IBM Corporation
  java.vendor.url = http://www.ibm.com/
  java.version = 1.8.0
  java.vm.info = JRE 1.8.0 z/OS s390x-64 Compressed References 20150630_255633 (JIT enabled, AOT enabled)
J9VM - R28_jvm.28_20150630_1742_B255633
JIT  - tr.r14.java_20150625_95081.01
GC   - R28_jvm.28_20150630_1742_B255633_CMPRSS
J9CL - 20150630_255633
  java.vm.name = IBM J9 VM
  java.vm.specification.name = Java Virtual Machine Specification
  java.vm.specification.vendor = Oracle Corporation
  java.vm.specification.version = 1.8
  java.vm.vendor = IBM Corporation
  java.vm.version = 2.8
  line.separator = 0x15
  os.arch = s390x
  os.encoding = ISO8859_1
  os.name = z/OS
  os.version = 02.02.00
  path.separator = :
  platform.notASCII = true
  sun.arch.data.model = 64
  sun.boot.class.path = ***
  sun.boot.library.path = ***
  sun.cpu.endian = big
  sun.io.unicode.encoding = UnicodeBig
  sun.java.command = ***
  sun.java.launcher = SUN_STANDARD
  sun.jnu.encoding = IBM-1047
  sun.security.policy.utf8 = false
  user.country = US
  user.dir = ***
  user.home = ***
  user.language = en
  user.name = ***
  user.timezone = GMT-05:00
  user.variant =

**Comment by gliptak** [comment]
@garydgregory This above is covered by this pull request.

**Comment by garydgregory** [comment]
See Git master for an alternate solution. You can close https://issues.apache.org/jira/browse/LANG-1146 and this issue if you like the solution and/or can test on z/OS.

**Pull request closed without merging**
