### PR TITLE
Replace the specified string with the one enclosed between two other strings(‘open’ and a ‘close’).

### PR DESCRIPTION
**Pull request by Yash-777**
Method Signature and Preconditions:

 * The method replaceSubstringInBetween takes four parameters: str, replace, open, and close. All parameters are marked as final and are expected to be non-null (@param comments indicate this precondition).
 * If any of the preconditions are violated (i.e., if str, open, close, or replace is null), the method simply returns the original str without any modifications.

### CODE REVIEW

**Comment by Yash-777** [comment]
recreated the Pull request of https://github.com/apache/commons-lang/pull/395

**Comment by garydgregory** [comment]
-1: This is such a niche use case that i don't think it belongs here. It is not even shown used within Commons Lang. The Javadoc shows no real word application as well IMO. This kind of text processing would not belong in Commons Lang anyway. We need to be careful and not grow this class into even more of a kitchen sink.

What do others think?

**Comment by 555vedant** [comment]
@garydgregory sir  i would like to work on it what is update of this PR ,
and  where i can find issue JIRA or issue template??

**Comment by garydgregory** [comment]
> @garydgregory sir i would like to work on it what is update of this PR , and where i can find issue JIRA or issue template??

Hello @555vedant, please see https://github.com/apache/commons-lang/pull/1239#issuecomment-2169714855

**Comment by sigee** [comment]
@Yash-777, @555vedant 
-1
In my opinion, replaceSubstringInBetween() is not needed. If you really need such replacements, RegExUtils.replacePattern() can do the same with proper parameters. I think.

**Comment by garydgregory** [comment]
Closing, no more dialog. Also, regular expressions built into Java is another option.

**Pull request closed without merging**
