### PR TITLE
Add toUnicodeString method to StringUtils for Unicode conversion

### PR DESCRIPTION
**Pull request by rahulcodespace**
Introduce a new method `toUnicodeString` to the `StringUtils` class. This method efficiently converts strings, especially those containing emojis or other special characters, to their Unicode representation.

- Utilizes the `codePointAt` method to cater to surrogate pairs.
- Ensures proper handling of empty strings.
- Returns the complete Unicode string with the respective prefix and formatted in hexadecimal.

This addition will aid in scenarios where a consistent Unicode representation of strings is required, enhancing the utility of the `StringUtils` class.

### CODE REVIEW

**Comment by garydgregory** [comment]
This duplicates Commons Lang and Text's `UnicodeEscaper` class.
-1 unless I am missing something.

**Comment by rahulcodespace** [comment]
> This duplicates Commons Lang and Text's `UnicodeEscaper` class. -1 unless I am missing something.



> This duplicates Commons Lang and Text's `UnicodeEscaper` class. -1 unless I am missing something.

`UnicodeEscaper` class has one method `protected String toUtf16Escape(final int codePoint)` but it takes codePoint as a argument and returns unicode string in hex form and I observed the entire class has been deprecated.

The `StringUtils.toUnicodeString()` takes `String` input and returns unicode string in hex form '\\uxxxx'

**Comment by rahulcodespace** [comment]
> Hello @rahulcodespace
> 
> Yes, this functionality is deprecated in Commons Lang, but, I also mentioned Commons **Text**, which is where the functionality is currently located and supported.
> 
> You might have failed to consider that the `UnicodeEscaper` and `UnicodeUnescaper` classes extend other classes that provide the class' full functionality.
> 
> Please look at the unit tests, and you'll see that this feature is already supported.

okay. Good to know that functionality already exists, I'm closing this PR.

This was my first attempt to cotribute to open source project. I would be happy to contribute to this repo in future.

Thank you.

**Comment by garydgregory** [comment]
Closing per @rahulcodespace comment.

**Pull request closed without merging**
