### PR TITLE
[LANG-1682] Adding new startsWithAnyIgnoreCase method and tests cases

### PR DESCRIPTION
**Pull request by laurentschoelens**
Adding new method startsWithAnyIgnoreCase method for case-insensitive version of startsWithAny

### CODE REVIEW

**Comment by garydgregory** [comment]
My preference is to stop adding APIs that are variations of other APIs based on the casing (and encoding and so on). In the longer term, I can see adding a new String utility class that tracks such an attribute on its instance such that you'd say something like `Strings.caseSensitive().someOperation(...)` and `Strings.caseInsensitive().someOperation(...)`.

**Comment by laurentschoelens** [comment]
Thanks for the reply.
Is there any plans for this ? It's huge refactoring.

**Comment by garydgregory** [comment]
It's something I'd like to do and might take a swing at when I am on vacation in April...

**Comment by laurentschoelens** [comment]
Like you expose the calling to this new Strings class, it looks like you're creating new instance (like a builder) and that should lead to memory impact and performances issues (as I see it)

**Comment by laurentschoelens** [comment]
> Like you expose the calling to this new Strings class, it looks like you're creating new instance (like a builder) and that should lead to memory impact and performances issues (as I see it)

If not, this could lead to thread-safety issues. But again I don't know what you want to do

**Comment by garydgregory** [comment]
@laurentschoelens 
Closing: Please try your use case with the Strings class in git master and snapshot builds.

**Comment by laurentschoelens** [comment]
I've seen your commit regarding the Strings class. I'm pretty sure that will do the job.
Thanks

**Pull request closed without merging**
