### PR TITLE
Add method to DiffBuilder to allow appending from a DiffResult.

### PR DESCRIPTION
**Pull request by NickManley**

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
@NickManley Thanks for the pull request.

It would be very nice if you would create a jira issue for this at: https://issues.apache.org/jira/browse/LANG/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel

**Comment by PascalSchumacher** [comment]
@NickManley Sorry I closed the wrong pull request. I meant to close #121 instead of this one.

Can you please reopen this one and close  #121?

Thanks!

**Comment by PascalSchumacher** [comment]
Issue to track this enhancement: https://issues.apache.org/jira/browse/LANG-1233

**Comment by NickManley** [comment]
I don't see any place on GitHub to reopen it once closed. I might need to make another pull request.

**Comment by PascalSchumacher** [comment]
Thanks for opening a new pull request :) and sorry again :(.

**Comment by PascalSchumacher** [comment]
Thanks! :+1:

**Pull request closed without merging**
