### PR TITLE
Use java stream in ArrayUtils.

### PR DESCRIPTION
**Pull request by arturobernalg**

### CODE REVIEW

**Comment by aherbert** [comment]
This seems like de-optimisation to me. The object creation overhead of the stream verses the simple for-loop constructs. I do not think it aids readability or maintainability.

**Comment by arturobernalg** [comment]
> This seems like de-optimisation to me. The object creation overhead of the stream verses the simple for-loop constructs. I do not think it aids readability or maintainability.

It seems that is what the API is tending towards.

**Comment by aherbert** [comment]
Using `Arrays.setAll` is not using a stream. It is offloading the for-loop into `Arrays` to work with a provided lambda function. This is not the same type of change.

**Comment by arturobernalg** [comment]
> Using `Arrays.setAll` is not using a stream. It is offloading the for-loop into `Arrays` to work with a provided lambda function. This is not the same type of change.

Should/must/have close the pr?

**Pull request closed without merging**
