### PR TITLE
[LANG-1547] fix code smells; fix typos

### PR DESCRIPTION
**Pull request by XenoAmess**

### CODE REVIEW

**Comment by XenoAmess** [comment]
Hi. 
I implemented a lastIndexOf in the last commit.
Maybe we should open another pr for it but...anyway.
if it is acceptable, then I will make the indexOf.
if not, then I will rebase it out.

**Comment by jochenw** [comment]
I'd find it reasonable to consider your changes in batches of, say, ten apiece. (That would make it possible to carefully inspect one by one.) But that many in one go? Definitely no.

**Comment by XenoAmess** [comment]
> I'd find it reasonable to consider your changes in batches of, say, ten apiece. (That would make it possible to carefully inspect one by one.) But that many in one go? Definitely no.

do you mean I should split them into several prs？

**Comment by XenoAmess** [comment]
the performance refines I said has being splited to [LANG-1548] and [LANG-1549]

**Comment by kinow** [comment]
> I'd find it reasonable to consider your changes in batches of, say, ten apiece. (That would make it possible to carefully inspect one by one.) But that many in one go? Definitely no.

@XenoAmess it's quite hard to review this PR. It has several commits, and several changes. Committers will have to read and understand your changes, and then be confident that these changes can go in the next release without causing regressions.

As @jochenw pointed out, instead if you could prepare one pull request for a change, and either include your other changes in another PR, or wait for a review/merge to submit more, that would be much easier to review; at the same time, your PR would be reviewed much faster.

Bruno

**Comment by XenoAmess** [comment]
> > I'd find it reasonable to consider your changes in batches of, say, ten apiece. (That would make it possible to carefully inspect one by one.) But that many in one go? Definitely no.
> 
> @XenoAmess it's quite hard to review this PR. It has several commits, and several changes. Committers will have to read and understand your changes, and then be confident that these changes can go in the next release without causing regressions.
> 
> As @jochenw pointed out, instead if you could prepare one pull request for a change, and either include your other changes in another PR, or wait for a review/merge to submit more, that would be much easier to review; at the same time, your PR would be reviewed much faster.
> 
> Bruno

OK, you're right, then I will split it into more prs.

**Comment by XenoAmess** [comment]
@jochenw  @kinow 
Hi.
This pr is already splited into several prs.
Most of them are small enough that not need to have a jira (IMO).
So I will close this pr.
Thanks for your help.

**Pull request closed without merging**
