### PR TITLE
Made String Reverse Method Faster

### PR DESCRIPTION
**Pull request by nishantc1527**
Right now, StringUtils.reverse() is done the lazy way by initializing a new Stringbuilder, calling reverse, then converting back into a string. I filled out the reverse method by doing it manually.

### CODE REVIEW

**Comment by XenoAmess** [comment]
Hi.
It actually breaks BC...
the original code can handle surrogate pairs.
you can see details in StringBuilder's source.

**Comment by XenoAmess** [comment]
besides, you should run a jmh test to show the performance incresement.
see HashSetvBitSetTest for example.

**Comment by nishantc1527** [comment]
> Hi.
> It actually breaks BC...
> the original code can handle surrogate pairs.
> you can see details in StringBuilder's source codes.

Sorry, I don't know what surrogate pairs are... do you mind explaining?

> besides, you should run a jmh test to show the performance incresement.
> see HashSetvBitSetTest for example.

Doing that now!

**Comment by garydgregory** [comment]
@XenoAmess 
Let's be careful with the terms we use here: this PR does NOT break BC. BC is about API signatures, not behavior.

**Comment by nishantc1527** [comment]
Never mind, I think ```StringBuilder```'s reverse method is better. Sorry for wasting anyone's time.

**Comment by XenoAmess** [comment]
> @XenoAmess
> Let's be careful with the terms we use here: this PR does NOT break BC. BC is about API signatures, not behavior.

@garydgregory Oh yes. thanks for the clarification.

**Pull request closed without merging**
