### PR TITLE
[LANG-1509] Add ObjectToStringComparator.

### PR DESCRIPTION
**Pull request by garydgregory**
Compares Object's `Object#toString()` values.
https://issues.apache.org/jira/browse/LANG-1509

### CODE REVIEW

**Comment by garydgregory** [comment]
Should it be Serializable?

**Comment by garydgregory** [comment]
@kinow I like the idea of putting it in a new package. What would you call it? "...compare"?

**Comment by garydgregory** [comment]
@kinow I moved it to `...compare` and I moved the new for 3.10 `ComparableUtils` there in master.

**Comment by kinow** [comment]
`.compare` sounds good to me. Couple of checkstyle issues in Travis now @garydgregory 

image

**Comment by garydgregory** [comment]
> `.compare` sounds good to me. Couple of checkstyle issues in Travis now @garydgregory
> 
> image

Oops, cleaned up now.

**Pull request merged**
