### PR TITLE
Implementations of the circuit breaker pattern related to LANG-1085

### PR DESCRIPTION
**Pull request by oheger**
These are the results of Bruno's and my collaboration on a circuit breaker implementation. For further discussions refer to LANG-1085.

commit 1b12db706b457408562a166c21bc6470a8064620
Merge: edebd97 def7832
Author: Oliver Heger <oliver.heger@oliver-heger.de>
Date:   Wed Jun 10 21:27:17 2015 +0200

    Merge pull request #1 from kinow/patch1

    This commit:

commit def78320c5efcb734572c5b48623a952e3c94c75
Author: Bruno P. Kinoshita <brunodepaulak@yahoo.com.br>
Date:   Wed Jun 10 22:57:33 2015 +1200

    This commit:

    * fixes JavaDocs warnings in Checkstyle
    * adds license headers
    * renames the MemoryCircuitBreaker to ThresholdCircuitBreaker
    * adds more tests to have a good coverage

commit edebd970582ce2984258352c8482bcb51587f7d2
Author: oheger <oliver.heger@oliver-heger.de>
Date:   Tue Jun 9 22:11:11 2015 +0200

    Documentation updates for EventCountCircuitBreaker.

commit 3d8a4ff85a78173dd8f5437d9b4d931069128e20
Author: oheger <oliver.heger@oliver-heger.de>
Date:   Tue Jun 9 21:55:02 2015 +0200

    Renamed TimedCircuitBreaker to EventCountCircuitBreaker.

    This name seems to be more appropriate as the main property of this circuit
    breaker implementation is that it counts specific events and changes its state
    when a certain threshold is reached.

commit 0e4ce5a984ef699ddace61bbf430d695b011c6b5
Author: oheger <oliver.heger@oliver-heger.de>
Date:   Tue Jun 9 21:51:22 2015 +0200

    Added documentation for CircuitBreaker interface.

commit 0e6b22190ef1868655fec9b3814a2345ad206f76
Author: oheger <oliver.heger@oliver-heger.de>
Date:   Mon Jun 8 22:27:05 2015 +0200

    Initial import of CircuitBreaker classes.

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
I guess this is ready to merge?

**Comment by oheger** [comment]
Well, the code is ready and fully unit-tested. When we created this pull request, we asked on the ML whether the lang concurrent package would be the right place for this code, but there was no reaction. So this question is still open.

**Comment by britter** [comment]
@oheger @PascalSchumacher: Nobody objected adding it to the concurrent package. So from PoV it can be integrated into LANG.

**Comment by PascalSchumacher** [comment]
Thanks! :+1:

**Pull request closed without merging**
