### PR TITLE
add tests for use ImmutableTriple as key in java.util.HashMap and java.util.TreeMap

### PR DESCRIPTION
**Pull request by apirom9**
add tests for use ImmutableTriple as key in java.util.HashMap and java.util.TreeMap

### CODE REVIEW

**Comment by kinow** [comment]
@apirom9 does this pull request number #379 supersedes yours previous one, number  #378? It looks to me like the tests from #378 are present in this pull request too? If so then we should close #378 to avoid confusion when reviewing & merging.

Thanks
Bruno

**Comment by apirom9** [comment]
@kinow Yes, it is. Sorry for my mistake, I already close pull request #378 

Thank you
Apirom

**Comment by kinow** [comment]
Generated site from `master` branch with `-Pjacoco`. Then stored the site elsewhere.

Checked out pull request locally. Squashed commits into a single one. Then rebased onto `master`. Generated site again, now from the pull request, and confirmed coverage went up, and build still passing OK. Code looks OK, so merging.

Thanks @apirom9 !
Bruno

**Comment by kinow** [comment]
Merged in https://github.com/apache/commons-lang/commit/bf7767867378d9d33551ad54687b48c8fbecf424

**Pull request closed without merging**
