### PR TITLE
[LANG-1627] Implement xorOneHot and add clarifications to Javadoc for xor to explain when it returns true

### PR DESCRIPTION
**Pull request by stevebosman-oc**
Contributed on behalf of the @opencastsoftware open source team

### CODE REVIEW

**Review by kinow — COMMENTED** [review]
Hi @stevebosman-oc 

I see there are two pull requests addressing LANG-1627. Any reason for not having a single PR?

Also, I think for such change it'd be doable to have everything in a single commit. So ideally it would be squashed by you, or a committer would have to do it if it's merged :+1: 

Thanks for your contribution!
-Bruno

**Comment by stevebosman-oc** [comment]
Hi, I'm happy to merge them. It was purely because they seemed to two distinct things. One improving the existing javadoc, and one adding additional functionality.

**Comment by kinow** [comment]
> Hi, I'm happy to merge them. It was purely because they seemed to two distinct things. One improving the existing javadoc, and one adding additional functionality.

Thanks, that's definitely good to try to split into separate pull requests when there are multiple tasks within an issue, but I think it should be fine to include the documentation/Javadoc clarification in the same PR. They can be squashed as a single commit too :+1:

**Comment by stevebosman-oc** [comment]
Merged two PRs and squashed. First time I've attempted a squash, please let me know if I've done anything wrong

**Comment by kinow** [comment]
>Merged two PRs and squashed.

Thanks!

>First time I've attempted a squash, please let me know if I've done anything wrong

It's perfect now! All that's left now is review the code :) thanks @stevebosman-oc !

**Pull request closed without merging**
