### PR TITLE
Added new example for containsAny method

### PR DESCRIPTION
**Pull request by esivakumar18**
Added new example for `containsAny` method

### CODE REVIEW

**Comment by garydgregory** [comment]
-1 this example won't even compile against this method.

**Comment by esivakumar18** [comment]
> -1 this example won't even compile against this method.

@garydgregory it does compile. I tested it on my machine and it works fine.

**Comment by garydgregory** [comment]
@esivakumar18 ... it compiles ... against a _different_ method than the one you are modifying.

**Comment by garydgregory** [comment]
No feedback, closing.

**Pull request closed without merging**
