### PR TITLE
adding power support

### PR DESCRIPTION
**Pull request by ghatwala**
enabling power builds for this repository via travis jobs.

### CODE REVIEW

**Comment by garydgregory** [comment]
How does testing Linux on Power test anything different for a given component compared to Linux on any other hardware?

**Comment by ghatwala** [comment]
> How does testing Linux on Power test anything different for a given component compared to Linux on any other hardware?

@garydgregory - Power(ppc64le) is a different architecture than the x86(intel) architecure . So it would be good to check for code regression on this . We have observed that many a times even though both are little endian arch's there are build/test case failures observed for any code on power which pass successfully on intel.

**Comment by kinow** [comment]
Conflict in `.travis.yml` now

**Comment by ghatwala** [comment]
@kinow - thanks for the update ..but this is still open PR , merged PR was this one - #435 .
@lysannef  - could you please check this  ?

**Pull request closed without merging**
