### PR TITLE
Add sugar to RandomIUtils

### PR DESCRIPTION
**Pull request by Punkratz312**

### CODE REVIEW

**Comment by britter** [comment]
Thank you!

**Comment by Punkratz312** [comment]
You´re welcome, thanks for merging.

Can you tell me, when the current snapshot will be released?

**Comment by britter** [comment]
@Punkratz312 I don't have a date for you. But I think I'll have some time in Nov/Dec to push out a release.

**Comment by Punkratz312** [comment]
Great - can’t wait to use the sugar.

Thanks for the answer.

**Pull request merged**
