### PR TITLE
[LANG-1681] Fix some FieldUtils Javadocs

### PR DESCRIPTION
**Pull request by laurentschoelens**
Fix for https://issues.apache.org/jira/browse/LANG-1681
Some methods using Validate.nonNull not refering to NullPointerException in javadoc comment

### CODE REVIEW

**Review by kinow — COMMENTED** [review]
Change looks good to me, thanks for creating it @laurentschoelens .

The issue says

>found 85 methods that throw NullPointerException 's but with a javadoc documenting an IllegalArgumentException.

but I am not sure if these methods were found only in [lang] or in all the dependencies the OP of that issue was using. Do you think this PR fixes the issue, or could there still be places where we are not reporting the NPE? In which case LANG-1681 would have to remain open.

Cheers

**Comment by dvmarcilio** [comment]
Thanks, @laurentschoelens for fixing these and @kinow for pinging me.
These 4 methods were among my tool findings.

I'm rerunning the tool on the latest commit. I'll be happy to submit more PRs fixing what it finds. Then we can finally close LANG-1681.
Should I submit one PR per class or a single (possibly large) PR for all findings?

The tool also finds missing `@throws`. I can submit different PRs for those as well.
Does that sound good to you, @kinow?

**Comment by kinow** [comment]
Hi @dvmarcilio 

>I'm rerunning the tool on the latest commit. I'll be happy to submit more PRs fixing what it finds. Then we can finally close LANG-1681.
>Should I submit one PR per class or a single (possibly large) PR for all findings?

That could result in a lot of similar PRs, which would spam others that follow every message/commit/etc sent to the ASF mailing lists. Would you be able to provide this list here? Then @laurentschoelens can see whether that can be added to this PR, or maybe you could send an extra commit/diff here.

As for the missing throws I think we can also add it here (noting that we have to verify first whether we document every runtime error or not - some libraries may decide to document everything, while others document only a few like NPE, IllegalArgument, etc).

Cheers
Bruno

**Comment by dvmarcilio** [comment]
@laurentschoelens, could you please give me permissions on your fork's branch `LANG-1681` so I can add more commits to it?

**Comment by laurentschoelens** [comment]
> @laurentschoelens, could you please give me permissions on your fork's branch `LANG-1681` so I can add more commits to it?

Could you tell me how to do it ?

**Comment by laurentschoelens** [comment]
> > Could you tell me how to do it ?
> 
> This should work: [Inviting collaborators to a personal repository](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository) However, I'm unsure if you can give permission to a single branch. If that's the case, I promise not to touch other branches :)

Done, enjoy 😃

**Comment by laurentschoelens** [comment]
Hi @kinow, work done by @dvmarcilio

**Comment by dvmarcilio** [comment]
I pushed modifications for all relevant cases that my tool could find.

**Comment by laurentschoelens** [comment]
> I pushed modifications for all relevant cases that my tool could find.

I'll do checks on this soon.
Many thanks for the job done

**Comment by kinow** [comment]
Great team work! I've triggered the workflow to run, and will take a look at this PR later today. Thanks :+1:

**Comment by kinow** [comment]
>Error:  src/test/java/org/apache/commons/lang3/reflect/FieldUtilsTest.java:[837] (regexp) RegexpSingleline: Line has trailing spaces.

**Review by kinow — APPROVED** [review]
We will have to look at the number of commits and either squash everything into a single commit, or maybe a couple/few. And add a changelog. But other than that, it's looking good IMO. There's a build issue due to an extra line, I think, but fixing that the build should pass. Thanks for adding tests that confirm the doc improvements too.

+1 from me. Let's wait and give time for others to review this too.

Thanks @laurentschoelens and @dvmarcilio !

**Comment by laurentschoelens** [comment]
@kinow : I'm not a git-pro but I'll squash the build fix with all commits of @dvmarcilio into one single commit and force-push to my repo if it's OK for you

**Comment by laurentschoelens** [comment]
> @kinow : I'm not a git-pro but I'll squash the build fix with all commits of @dvmarcilio into one single commit and force-push to my repo if it's OK for you

Done. And build should be fixed

**Pull request merged**
