### PR TITLE
[LANG-1609] - Case-insensitive variants for startsWithAny and endsWithAny

### PR DESCRIPTION
**Pull request by arturobernalg**
Add methods to StringUtils class
StringUtils::startsWithAnyIgnoreCase(CharSequence, CharSequence...)
StringUtils::endsWithAnyIgnoreCase(CharSequence, CharSequence...)

### CODE REVIEW

**Comment by arturobernalg** [comment]
Hi @garydgregory 
ping here ;)

**Comment by XenoAmess** [comment]
@garydgregory @arturobernalg I remembered gary had a plan to due with all ignoreCase functions differently, in lang4. 
Also, should this function be added directly to commons-text instead of commons-lang?

**Comment by garydgregory** [comment]
> @garydgregory @arturobernalg I remembered gary had a plan to due with all ignoreCase functions differently, in lang4.
> Also, should this function be added directly to commons-text instead of commons-lang?

Good reminder @XenoAmess 
I want us to think about what belongs in Lang vs. Text. IMO when we talk about "case", we talk about Text. As opposed to a String which is a wrapper for an array. So I think I'd like to see case operations in Text. Needs more study... I certainly don't want to keep growing StringUtils beyond it's current kitchen sink style.

**Comment by arturobernalg** [comment]
Hi @garydgregory  @XenoAmess 
I really didn't know that. How can I know those things?
So, and now? What do I do with the PR?do i need close the PR?

**Comment by garydgregory** [comment]
In general, information is spread about on the dev mailing list, PR comments, and JIRA tickets. The dev ML has the most history information I would say but JIRAs and PRs are also important. Remember that this is a volunteer based organization and that we do our best :-)

**Comment by nstdio** [comment]
Is this same #630 ?

**Pull request closed without merging**
