### PR TITLE
LANG-1060: NumberUtils.isNumber assumes number starting with Zero

### PR DESCRIPTION
**Pull request by piotrkosyoo**
NumberUtils.isCreatable("002.345"); return false

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Thanks! 👍

**Comment by piotrkosyoo** [comment]
No problem Sir,
Calling Number.to Float also works correctly, and I skip this point.  but maybe
 better is add the tests for this case?

**Comment by PascalSchumacher** [comment]
A pull request with tests for the `float` case would be welcome.

**Comment by piotrkosyoo** [comment]
ok in this same issue number ?

**Comment by PascalSchumacher** [comment]
Sure, that is fine!

**Pull request closed without merging**
