### PR TITLE
Add IsAllEmpty and isAllBlank methods

### PR DESCRIPTION
**Pull request by martin-tarjanyi**
* Fix javadoc

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Thanks for the pull request. :)

I guess we better class theses methods `areAllEmpty`/`areAllBlank`. What do you think?

**Comment by martin-tarjanyi** [comment]
The names you suggest express the use cases better, I agree.  

The only thing I'm afraid of is that people might have a difficult time finding them since most of the blank/empty methods start with 'is'. 

I'll change it, though. 

Other topic: what do you think of the handling of empty array or null as a single parameter? Is it right to return true in these cases?

Can I use git rebase to add changes or brand new commits are the preferred way?

**Comment by dmjones500** [comment]
I vote strongly for `is*` method naming. That's the convention for Java methods of this type, even if it slightly upsets the English ear.

**Comment by PascalSchumacher** [comment]
>I vote strongly for is* method naming. That's the convention for Java methods of this type, even if it slightly upsets the English ear.

Then let's keep is* names.

>Other topic: what do you think of the handling of empty array or null as a single parameter? Is it right to return true in these cases?

I'm not sure what the behavior should be in these cases. @dmjones500 / anybody else: any opinions on this?

**Comment by PascalSchumacher** [comment]
I have created an jira issue for this: https://issues.apache.org/jira/browse/LANG-1293 and also asked for opinions on the empty/null array question there.

**Comment by dmjones500** [comment]
I commented on the naming conventions without actually reviewing the change...

I don't think we should add methods that are simply the inverse of another method. It bloats the code base for no real gain.

I wouldn't be in favour of committing these new methods. The Javadoc fix is welcome, of course!

**Comment by martin-tarjanyi** [comment]
So if this method is not added to the codebase but I would like to have this functionality in my client code, then I should call ``!isAnyNotEmpty(...)``. It would be very difficult to read. That's why I thought these methods would be useful. 

However, if I should choose between ``isAllEmpty`` and ``isAnyNotEmpty`` to be in StringUtils, I would support ``isAllEmpty`` because the negated version ``!isAllEmpty`` is more readable in a client code.

What do you think?

**Comment by PascalSchumacher** [comment]
If only one method is added it should be `isAll*` instead of `isAnyNot*`. Since the `isAnyNot*` are not released yet, they can be removed.

I personally would have no problem with adding both types of methods. Making client code more readable is imho enough to justify the addition.

**Comment by PascalSchumacher** [comment]
On further consideration, there are already methods with are "simply the inverse of another method": `isEmpty/isNotEmpty`, `isAnyEmpty/isNoneEmpty`, `containsAny/containsNone`. I will start a discussion on the mailing list.

**Comment by martin-tarjanyi** [comment]
Hi @PascalSchumacher,
Is there any update on this matter? Should I change something?

**Comment by PascalSchumacher** [comment]
@martin-tarjanyi Sorry for the delay. :( I finally send a mail to the mailing list:

https://mail-archives.apache.org/mod_mbox/commons-dev/201702.mbox/%3C13256228-1650-e98e-fe93-22801e530c88%40gmx.net%3E

**Pull request closed without merging**
