### PR TITLE
Remove redudant argument from substring call

### PR DESCRIPTION
**Pull request by bhawna94**
Remove redundant parameter:str.length() as by default substring(int beginIndex) method returns the substring from the specified index and extends till string length. 
And as str.length() is final.So, storing str.length() into a variable final int length = str.length() to avoid calling function str.length() sevaral times.

### CODE REVIEW

**Comment by bhawna94** [comment]
@britter @garydgregory @chtompki @kinow Please review the PR and let me know your thoughts as well.

**Comment by bhawna94** [comment]
Thanks @kinow . Are we good to merge this or waiting for other approvals

**Comment by kinow** [comment]
Not a problem @bhawna94 , I think it should be ready to be merged, I'm just looking at other PR's at the moment, but can probably merge in some moments :+1:

**Comment by bhawna94** [comment]
Thanks for the update @kinow

**Comment by kinow** [comment]
Merged. Thanks @bhawna94 !

**Pull request merged**
