### PR TITLE
Use Set instead of List for checking the contains() method

### PR DESCRIPTION
**Pull request by CiprianBodnarescu**
Use the HashSet collection for using the **contains()** method on the given Locale object.
The change improves the time complexity of this method from O(n) for ArrayList to O(1) for HashSet

### CODE REVIEW

**Review by XenoAmess — APPROVED** [review]
LGTM

**Comment by CiprianBodnarescu** [comment]
Hello 😄. Is there something else needed here in order to merge this PR?

**Comment by garydgregory** [comment]
> Hello 😄. Is there something else needed here in order to merge this PR?

Patience ;-) we are volunteers. I'd rather get help fixing the build on Java 16 before reviewing PRs.

**Comment by XenoAmess** [comment]
> Hello 😄. Is there something else needed here in order to merge this PR?

I had a pr delayed for 360 days...

And 10+ other delayed for several months.

So, please be patient.

**Comment by CiprianBodnarescu** [comment]
Understood 👍 . It is my first contribution and I wanted to be sure I don't do anything wrong. Thank you 😄

**Pull request merged**
