### PR TITLE
LANG-1300: Change CharSequenceUtils to support supplementary characters

### PR DESCRIPTION
**Pull request by MarkDacek**
@chtompki 
I'm tackling the root cause now.

### CODE REVIEW

**Comment by chtompki** [comment]
Definitely looking better than #250. I'm fiddling around with this locally currently. I'll keep you posted.

@dmjones500 - Since you logged LANG-1300, you have any thoughts on this one?

**Comment by dmjones500** [comment]
Sorry @chtompki, I've been crazy busy lately and haven't moved many issues forward at all.

These changes look good. One thing I've noticed (which is no fault of this change) is the method behaves differently if the input is a String. `String.indexOf(int ch)` returns the index, as measured by _code points_. However the remainder of the method will return the index measured in _code units_.

I haven't had the time to prove this with a unit test, but might be worth looking into this at the same time.

**Comment by dmjones500** [comment]
@chtompki  I'm far from a complexity expert, but if we keep a running tally of the current index in terms of code points, I don't see us going from _O(n)_ to _O(n<sup>2</sup>)_. Wouldn't _O(n<sup>2</sup>)_ imply that for each item in the input, we traverse the entire input again?

**Comment by chtompki** [comment]
@dmjones500 - You're correct there, I wasn't thinking about it properly because I was thinking in terms of `lastIndexOf` moving in from the end of the `CharSequence` and then having to traverse in from the beginning to sort out the number of surrogate pairs in the prefix to the matching character. But, if you simply start with that traversal, then you remain at *O(n)*.

**Comment by MarkDacek** [comment]
Just a question I have on this. 
Are we to do this for ALL calls to this method, or only those where the search char is a supplementary char?

**Comment by MarkDacek** [comment]
@chtompki Please look this over. We have some interesting conflicts here.
1. The issue mentioned above. indexOf("a") will double-count surrogate-pairs if they exist. We can fix this if need be.
2. A string with two surrogate-pairs will read as length 4, though we will treat it as length 2 for the purpose of these operations. E.G. : 
       ```
        final int CODE_POINT = 0x2070E;
    	StringBuilder builder = new StringBuilder();
    	builder.appendCodePoint(CODE_POINT);
        builder.appendCodePoint(CODE_POINT);
       StringUtils.lastIndexOf(builder, CODE_POINT, 2) 
```
the bottom line will return -1, wheras the builder.toString()... version returns 2. I suspect this is just that they disregarded our issue and start at charAt(2) instead of our iterative approach here.

**Comment by dmjones500** [comment]
We need to agree on the desired behaviour of the method. Based on the signature, I think we can adjust it to support supplementary characters without violating the implied contract of the method. The issue for me is about indexes.

Based on the JavaDoc description, I suggest we return the code unit index. This is because the input is a `CharSequence` and the JavaDoc states:

> Finds the first index within a `CharSequence`, handling null.

Also, a `CharSequence` only has methods which operate on code unit indexes. So returning a code unit index would be helpful for further operations on the sequence.

What does everyone else think? We should obviously update the JavaDocs to make it crystal clear what we decide, either way.

**Comment by chtompki** [comment]
@dmjones500 - you think we should bubble this up to the dev list?

**Comment by chtompki** [comment]
Okay. It seems that we'll want some clearer documentation. Note that the javadoc on `indexOf` in the jdk follows:

```java
/**
     * Returns the index within this string of the first occurrence of the
     * specified character, starting the search at the specified index.
     * <p>
     * If a character with value <code>ch</code> occurs in the
     * character sequence represented by this <code>String</code>
     * object at an index no smaller than <code>fromIndex</code>, then
     * the index of the first such occurrence is returned. For values
     * of <code>ch</code> in the range from 0 to 0xFFFF (inclusive),
     * this is the smallest value <i>k</i> such that:
     * <blockquote><pre>
     * (this.charAt(<i>k</i>) == ch) && (<i>k</i> &gt;= fromIndex)
     * </pre></blockquote>
     * is true. For other values of <code>ch</code>, it is the
     * smallest value <i>k</i> such that:
     * <blockquote><pre>
     * (this.codePointAt(<i>k</i>) == ch) && (<i>k</i> &gt;= fromIndex)
     * </pre></blockquote>
     * is true. In either case, if no such character occurs in this
     * string at or after position <code>fromIndex</code>, then
     * <code>-1</code> is returned.
     *
     * <p>
     * There is no restriction on the value of <code>fromIndex</code>. If it
     * is negative, it has the same effect as if it were zero: this entire
     * string may be searched. If it is greater than the length of this
     * string, it has the same effect as if it were equal to the length of
     * this string: <code>-1</code> is returned.
     *
     * <p>All indices are specified in <code>char</code> values
     * (Unicode code units).
     *
     * @param   ch          a character (Unicode code point).
     * @param   fromIndex   the index to start the search from.
     * @return  the index of the first occurrence of the character in the
     *          character sequence represented by this object that is greater
     *          than or equal to <code>fromIndex</code>, or <code>-1</code>
     *          if the character does not occur.
     */
```

Let's see if we can get something along these lines on both CharSequenceUtils as well as StringUtils. Furthermore, I think we should stick as closely to the implementation in `String` as possible simply generalizing to `CharSequence`'s.

**Comment by MarkDacek** [comment]
Chiming in here. I'd recommend using code units so that it's compatible with the other operations like substring. Of course, this would still break if you called substring(index+1) since you'd be taking the second byte of a supplementary character, but I'd still argue that this is the path to take.

**Comment by chtompki** [comment]
I'm going to make some documentation changes here. I'll keep you apprised as I make them.

**Comment by chtompki** [comment]
Going to fix the javadoc build and then pull this in.

**Pull request merged**
