### PR TITLE
Remove redundant parameter: str.length()

### PR DESCRIPTION
**Pull request by bhawna94**
Remove redundant parameter:str.length() as by default substring(int beginIndex) method returns the substring from the specified index and extends till string length.

### CODE REVIEW

**Comment by bhawna94** [comment]
@kinow Could you please review the PR and let me know your thoughts.

**Comment by XenoAmess** [comment]
Hi.
I agree with this pr, but I think you can do it more aggressively.
You see, in this function, param `str` is final, thus `str.length()` is final.
Why don't we let a `final int length = str.length()` to avoid calling function `str.length()` sevaral times?
Any ideas guys?

**Comment by garydgregory** [comment]
Seems reasonable to only call length() once if str is final.

**Comment by bhawna94** [comment]
Agreed! @XenoAmess @garydgregory

**Comment by bhawna94** [comment]
Updated the PR. Please have a look

**Pull request closed without merging**
