### PR TITLE
ObjectUtils::xorNull added

### PR DESCRIPTION
**Pull request by cezarykluczynski**
Seems useful. What's your opinion?

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Thanks for the pull request!

I'm not sure this is generally useful. I do not remember ever needing/using a method like this.

**Comment by dmjones500** [comment]
@cezarykluczynski Can you suggest a few use cases for this functionality in a normal application?

**Comment by cezarykluczynski** [comment]
@dmjones500 I'm not sure what you mean by normal application, but here are two examples: https://github.com/cezarykluczynski/stapi/search?utf8=%E2%9C%93&q=xorNull

**Comment by dmjones500** [comment]
@cezarykluczynski Commons Lang solves frequently encountered programming problems by adding methods that are arguably "missing" from `java.lang`. I'm trying to imagine the sort of problem this solves.

You've provided two examples. Looking at them, I'm not sure whether `xorNull` is the best way to solve them.

Based on the name of the method, I would have thought this might work:

```java
private void removeBirthNameIfItEqualsName(ActorTemplate actorTemplate) {
    String name = actorTemplate.getName();
    String birthName = actorTemplate.getBirthName();

    if (birthName == null) {
        return;
    }

    if (birthName.equals(name)) {
        actorTemplate.setBirthName(null);
    }
}
```

In your other example, you could rearrange the conditional statements and remove the need for your method:

```java
private LocalDate getIfEqualSkipNulls(LocalDate left, LocalDate right, Page item, boolean dateOfBirth) {

    if (left == null && right == null) {
        return null;
    } else if (left != null && right != null) {
        if (left.equals(right)) {
            return left;
        } else {
            String dateType = dateOfBirth ? "birth" : "death";
            log.error(
                    "Date of {} {} from for PageToLifeRangeProcessor does not equal date of {} {} from "
                            + "ActorTemplateToLifeRangeProcessor for {} - setting date to null",
                    dateType, left, dateType, right, item.getTitle());
            return null;
        }
    } else {
        return ObjectUtils.firstNonNull(left, right);
    }
}
```

**Pull request closed without merging**
