### PR TITLE
Longs

### PR DESCRIPTION
**Pull request by mureinik**
Style improvement for handling long literals throughout the project.

This patch contains:
- Using long literals instead of casting int literals
- Using uppercase L to signify long literals

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Thanks! :+1:

**Comment by mureinik** [comment]
@PascalSchumacher Using uppercase L for long literals can also easily be enforced by checkstyle. Should I add this check, or would that be more of a nuisance than it's worth?

**Comment by PascalSchumacher** [comment]
+1 to adding the check

**Comment by mureinik** [comment]
@PascalSchumacher I posed PR #249 to do so, thanks.

**Pull request closed without merging**
